services:
  - type: web
    name: arielmatrix-ai
    runtime: node22
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVarGroups:
      - id: arielmatrix-secrets
        required: true
    healthCheckPath: /api/cosmoweb3db

  - type: webhook
    name: cosmoweb3db
    triggerPath: /api/cosmoweb3db
    runtime: python3.11
    entrypoint: python api/cosmoweb3db.py

  - type: cron
    name: revenue-cron
    schedule: "*/10 * * * *"
    command: curl -X POST https://arielmatrix-ai.onrender.com/api/orchestrator -H "Content-Type: application/json" -d '{"action":"run"}'
